### ISSUE TITLE
Random 30 second delays

### ISSUE THREAD

**Issue by bansalvivek** [codelibs/spnego#5]
Hi there,

Thanks for the library. We are getting random 30 second delays. Think we are using the 2016 version of this library but there is no way to tell as the original developer has left us long time ago. I know it is a shot in the dark but by any chance would you know if the library could be causing that delay. 

Thanks for your help.
Kind regards

**Comment by marevol** [comment]
We do not see the problem.
To find the cause, it's better to take thread dumps with jstack several times.

**Comment by bansalvivek** [comment]
Thanks for getting back to me. Appreciate it There is a thread.delay for 31 seconds on line 367 in SpnegoHTTPUrlConnection class. Can you please tell me what does that do?

Thanks again.

**Comment by marevol** [comment]
https://github.com/codelibs/spnego/blob/master/src/main/java/org/codelibs/spnego/SpnegoHttpURLConnection.java#L367 is a blank line.
What version did you use? It's better to replace with the latest version.

**Comment by bansalvivek** [comment]
Sorry had a long night. The correct line number is 376.

**Comment by marevol** [comment]
I think the cause seems to be a lot of simultaneous accesses.

**Comment by bansalvivek** [comment]
I think you are right. Lot of concurrent requests could be causing this behaviour. So this line of the code in your library makes threads wait for 31 seconds when there are lot of concurrent requests?

Regards,
Vivek

**Comment by marevol** [comment]
It's 31 millisecond, not 31 second.
The cause is SpnegoHttpURLConnection.LOCK.lock() blocks threads.
